In [8]:
import os
from glob import glob
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [5]:
active_dir = '/Users/johnnycortez/Documents/springboard/data'
os.chdir(active_dir)

In [6]:
os.listdir()

['ZIP-COUNTY-FIPS.txt',
 'tax_data_2018.txt',
 'Headers_2017.docx',
 'Headers_2016.docx',
 'Headers_2015.docx',
 'Headers_2018.docx',
 'Headers_2014.docx',
 'tax_data_2015.txt',
 'tax_data_2014.txt',
 'tax_data_2016.txt',
 'tax_data_2017.txt']

In [9]:
year_2014 = pd.read_csv('tax_data_2014.txt')

In [37]:
header_2014 = pd.read_csv('header_2014.csv')
header_2014

,VARIABLE NAME,DESCRIPTION,Unnamed: 2,VALUE/LINE REFERENCE,Unnamed: 4,Type
0,STATEFIPS,The State Federal Information Processing Syste...,NaN,01-56,NaN,Char
1,STATE,The State associated with the ZIP code,NaN,Two-digit State abbreviation code,NaN,Char
2,ZIPCODE,5-digit Zip code,NaN,,NaN,Char
3,AGI_STUB,Size of adjusted gross income,NaN,"1 = $1 under $25,000 2 = $25,000 under $50,000...",NaN,Num
4,N1,Number of returns,NaN,,NaN,Num
...,...,...,...,...,...,...
124,A11901,Tax due at time of filing amount [10],NaN,1040:78 / 1040A:50 / 1040EZ:14,NaN,Num
125,N11902,Number of returns with overpayments refunded,NaN,1040:75 / 1040A:47 / 1040EZ:13a,NaN,Num
126,A11902,Overpayments refunded amount [11],NaN,1040:75 / 1040A:47 / 1040EZ:13a,NaN,Num
127,NaN,NaN,NaN,NaN,NaN,NaN
128,NaN,NaN,NaN,NaN,NaN,NaN

In [38]:
header_2014_definitions = header_2014[['VARIABLE NAME', 'DESCRIPTION']]

In [45]:
header_2014_definitions

    VARIABLE NAME                                        DESCRIPTION
0       STATEFIPS  The State Federal Information Processing Syste...
1           STATE             The State associated with the ZIP code
2         ZIPCODE                                   5-digit Zip code
3        AGI_STUB                      Size of adjusted gross income
4              N1                                  Number of returns
..            ...                                                ...
124        A11901            Tax due at time of filing amount [10]
125        N11902       Number of returns with overpayments refunded
126        A11902                Overpayments refunded amount [11]
127           NaN                                                NaN
128           NaN                                                NaN

[129 rows x 2 columns]